{
 "title": "Business Metrics",
 "panels": [
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chirp_users_total_value" }
   ]
  },
  {
   "title": "Total Cheeps",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chirp_cheeps_value" }
   ]
  },
  {
   "title": "Top 10 Users (Cheeps)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    { "expr": "top10_cheeps_value" }
   ]
  }
 ]
}