{
 "title": "Chirp",
 "tags": [ "chirp" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Chirp Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cheeps Created (total)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "chirp_cheeps_created_total", "legendFormat": "Cheeps created" }
   ]
  },
  {
   "title": "Comments Added (total)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "chirp_comments_added_total", "legendFormat": "Comments added" }
   ]
  },
  {
   "title": "Cheeps Creation Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(chirp_cheeps_created_total[5m])",
     "legendFormat": "Cheeps/s"
    }
   ]
  },
  {
   "title": "Comments Creation Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(chirp_comments_added_total[5m])",
     "legendFormat": "Comments/s"
    }
   ]
  }
 ]
}