name: DevSkim Security Scan

on:
  push:
    branches:
      - main


jobs:
  devskim:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Install DevSkim
        run: dotnet tool install --global Microsoft.CST.DevSkim.CLI

      - name: Run DevSkim scan
        run: devskim analyze -I src/ \
              --ignore "Chirp.Razor/Properties/launchSettings.json" \
              --ignore "Chirp.Razor/appsettings.json" \
              --exit-code \
              -f text
